### ISSUE TITLE
Feature: Improve README.md 

### ISSUE THREAD

**Issue by FlorianFrank** [FlorianFrank/climate_chamber_control_lib#7]
Add additional information, e.g. how to checkout the repo, how to build it and give an overview over the most important functions.

**Comment by chrisghu** [comment]
Hi Florian, thanks for this lib. Trying to compile it under windows to use the python wrapper. Do you already have a quick overview how to do that? Is there any API description for the Weiss chambers? How did you implement the control of the chambers? Can you help me out with some information. Thanks in advance. Br, Christian

**Comment by FlorianFrank** [comment]
Hi Chris, 

I didn't really find a description of the API so implementing this library was more or less try and error. I used the library for a project one year ago and didn't do much on it but I try to add a description on how to compile the library and how to call the functions probably today to the README.md file, so that you can easily clone, compile and run some functions. 
Best
Florian

**Comment by FlorianFrank** [comment]
> Hi Florian, thanks for this lib. Trying to compile it under windows to use the python wrapper. Do you already have a quick overview how to do that? Is there any API description for the Weiss chambers? How did you implement the control of the chambers? Can you help me out with some information. Thanks in advance. Br, Christian

Hi Christian, 
maybe you can checkout the newes release of this project. There you should find all packages required to run the library on windows. 
I additionally adjusted the project description. There you can find a documentation of the API, how to compile and run programs using the lib. If you have any questions just contact me. 
Best
Florian
